services:
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_DATABASE: bar_inventory
  #     MYSQL_USER: bar_user
  #     MYSQL_PASSWORD: bar_password
  #     MYSQL_ROOT_PASSWORD: root_password
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10

  web:
    build:
       context: ./
       dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8332
    environment:
      - DJANGO_ENV=dev
      - DB_HOST=db
      - DB_NAME=bar_inventory
      - DB_USER=bar_user
      - DB_PASSWORD=bar_password
      - DB_PORT=3306
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ./code:/code
    ports:
      - "8332:8332"
    # depends_on:
    #   db:
    #     condition: service_healthy

volumes:
  mysql_data:
